import { part1, part2 } from '../solutions/day07';
import { readFileSync } from 'fs';
import { join } from 'path';

describe('day07', () => {
  const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;
  const realInput = readFileSync(join('inputs', 'day07.txt'), 'utf8');

  test('part1 - example', () => {
    expect(part1(exampleInput)).toBe(21);
  });

  test('part2 - example', () => {
    expect(part2(exampleInput)).toBe(40);
  });

  test('part1 - real input', () => {
    expect(part1(realInput)).toBe(1499);
  });

  test('part2 - real input', () => {
    expect(part2(realInput)).toBe(24743903847942);
  });
});
